/*
 * Generated by MTK SP DrvGen Version: 3.5.160809 for MT6739.
 * 2019-11-11 10:46:44
 * Do Not Modify The File.
 * Copyright Mediatek Inc. (c) 2016.
*/

#ifndef __CUST_ADC_H
#define __CUST_ADC_H

#define AUXADC_TEMPERATURE_CHANNEL			0
#define AUXADC_TEMPERATURE1_CHANNEL			1
#define AUXADC_ADC_FDD_RF_PARAMS_DYNAMIC_CUSTOM_CH_CHANNEL			12


#endif /* __CUST_ADC_H */
